# Generated by Django 3.2.9 on 2021-11-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211111_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='PRDIImage',
            field=models.ImageField(upload_to='IMAGE', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATMain_Category', models.CharField(max_length=100)),
                ('CAtDesc', models.TextField()),
                ('CATimg', models.ImageField(upload_to='category/')),
                ('CATParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
