# Generated by Django 3.2.9 on 2021-11-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_catparent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorry', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.CreateModel(
            name='Product_Alterative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNProducte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Product', to='product.product')),
                ('PLANAlterative', models.ManyToManyField(related_name='Alterative_Product', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Alterative',
                'verbose_name_plural': 'Product Alteratives',
            },
        ),
    ]
