# Generated by Django 3.2.9 on 2021-11-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211113_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAccessories', models.ManyToManyField(related_name='Accessories_Product', to='product.Product')),
                ('PACCProducte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainAccessories_Product', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Accessories',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
