# Generated by Django 3.2.9 on 2021-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20211114_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
