# Generated by Django 3.2.8 on 2021-11-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDBestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='PRDNew',
            field=models.BooleanField(default=True),
        ),
    ]
