# Generated by Django 3.2.9 on 2021-11-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDName',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
